blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/jsrivaya/loon/discussions
    about: For questions and discussions, please use GitHub Discussions instead of opening an issue.
